
INSERT INTO roles (nom) VALUES
    ('Assassin'),
    ('Combattant'),
    ('Mage'),
    ('Tireur'),
    ('Support'),
    ('Tank');

INSERT INTO champions (name, difficulte, description, price, stock, reduction, devise, genre, espece)
VALUES
    ('Aatrox',
    'Difficile',
    "Autrefois, Aatrox et ses frères étaient honorés pour avoir défendu Shurima contre le Néant. Mais ils finirent par devenir une menace plus grande encore pour Runeterra : la ruse et la sorcellerie furent employées pour les battre. Cependant, après des siècles d'emprisonnement, Aatrox fut le premier à retrouver sa liberté, en corrompant et transformant les mortels assez stupides pour tenter de s'emparer de l'arme magique qui contenait son essence. Désormais en possession d'un corps qu'il a approxim",
    880,
    50,
    0.00,
    'RP',
    'Masculin', 
    'darkin'),
    ('Ahri',
    'Moyen',
    "Connectée à la magie du royaume spirituel, Ahri est une mystérieuse Vastaya aux traits de renard qui peut manipuler les émotions de sa proie et consumer son essence, afin de recevoir des fragments de sa mémoire. Ahri fut un temps un terrifiant prédateur, mais elle voyage désormais à la recherche des vestiges de ses ancêtres tout en essayant de remplacer les souvenirs qu'elle a volés par sa propre expérience de l'existence.", 
    880, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'vastaya'),
    ('Akali',
    'Difficile',
    "Ayant abandonné l'Ordre Kinkou et le titre de Poing de l'ombre, Akali combat aujourd'hui seule, prête à devenir l'arme mortelle dont son peuple a besoin. Bien qu'elle n'oublie rien de tout ce que son maître Shen lui a enseigné, elle a juré de défendre Ionia contre ses ennemis, une élimination après l'autre. Akali tue sans faire de bruit, mais son message est fort et clair : craignez l'assassin sans maître.", 
    880, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Akshan',
    'Difficile',
    "Se jouant du danger, Akshan combat le mal sans jamais se départir de son charisme (il ne faut jamais sous-estimer l'importance de la cape) et de sa droiture. Il est passé maître dans l'art du combat furtif, ce qui lui permet d'échapper au regard de ses ennemis et de réapparaître lorsqu'ils s'y attendent le moins. À l'aide de son sens aigu de la justice et d'une arme légendaire défiant la mort elle-même, il redresse les torts des nombreux vauriens de Runeterra. Sa règle d'or : « ne sois pas crapu", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Alistar',
    'Facile',
    "Alistar est un guerrier redoutable cherchant à se venger de l'empire noxien qui a détruit son clan. Bien qu'il ait été réduit en esclavage et forcé de vivre une vie de gladiateur, sa volonté de fer lui a permis de ne pas succomber à la folie bestiale qui le menaçait. Maintenant qu'il a retrouvé la liberté, il combat au nom des faibles et des opprimés. Ses seules armes sont ses cornes, ses sabots et ses poings.", 
    585, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'autre'),
    ('Ambessa',
    'Difficile',
    "Tous ceux qui connaissent le nom de Medarda savent qu'il faut craindre et respecter sa matriarche, Ambessa. En tant que générale noxienne, elle incarne la force impitoyable et la détermination sans peur. Son rôle de matriarche n'est pas bien différent. Elle se doit de faire preuve d'une grande ruse tout en ne laissant aucune place à l'échec ou à la compassion. Dédiée à la voie du Loup, Ambessa fera tout ce qui est en son pouvoir pour protéger l'héritage de sa famille, même si cela doit lui coûte", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Amumu',
    'Facile',
    "La légende veut qu'Amumu soit une âme solitaire et mélancolique de la Shurima antique et qu'il parcoure le monde à la recherche d'un ami. Condamné par une malédiction à rester seul à jamais, il provoque la mort et la ruine à chaque geste d'affection. Ceux qui prétendent l'avoir vu le décrivent comme un cadavre vivant, petit de taille, enveloppé dans d'effrayants bandages. Il a inspiré bien des mythes, des chansons et des légendes, transmis de génération en génération pendant si longtemps qu'il e", 
    260, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'yordle'),
    ('Anivia',
    'Moyen',
    "Anivia est un esprit ailé bienveillant qui subit des cycles sans fin de vie, de mort et de renaissance pour protéger Freljord. Demi-déesse née de la glace la plus froide et des vents les plus coupants, elle utilise ses pouvoirs élémentaires contre quiconque prétend troubler la paix de sa terre natale. Anivia guide et protège les tribus du Nord, qui la vénèrent comme un symbole d'espoir et la promesse de grands changements. Elle combat de tout son être, sachant que son sacrifice fera vivre sa lég", 
    790, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'dieu'),
    ('Annie',
    'Facile',
    "Dangereuse, incroyablement précoce, Annie est une enfant mage dotée d'extraordinaires pouvoirs de pyrokinésie. Même à l'ombre des montagnes du nord de Noxus, sa magie est un cas unique. Son affinité naturelle avec le feu se manifesta dès sa prime enfance à travers des explosions émotionnelles imprévisibles, même si elle apprit rapidement à contrôler ces éclats. Parmi ses jeux favoris, elle aime invoquer son bien-aimé ours en peluche, Tibbers, sous la forme d'un protecteur enflammé. Perdue dans l", 
    260, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Aphelios',
    'Difficile',
    "Émergeant des ombres au clair de lune, Aphelios abat ceux qui voudraient anéantir sa foi sans un mot ; ses armes et sa précision mortelle parlent pour lui. Un poison qui le rend muet coule dans ses veines, mais il est constamment guidé par sa sœur, Alune. Depuis son temple lointain, elle lui confère un arsenal d'armes en pierre de lune. Tant que la lune brillera dans le ciel, Aphelios ne sera jamais seul.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Ashe',
    'Facile',
    "Chef de guerre sublimé de la tribu des Avarosans, Ashe est à la tête de la plus vaste horde des terres du nord. Stoïque, intelligente et idéaliste, mais mal à l'aise dans son rôle de leader, elle puise dans la magie ancestrale de sa lignée pour manier un arc de glace pure. Soutenue par son peuple qui voit en elle la réincarnation de la légendaire héroïne Avarosa, Ashe cherche à unifier Freljord en reprenant les terres tribales.", 
    260, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('AurelionSol',
    'Moyen',
    "Autrefois, Aurelion Sol façonnait des merveilles célestes dont il parsemait le vide infini du cosmos. À présent, il est forcé d'utiliser ses pouvoirs extraordinaires pour le compte d'un empire de l'espace qui s'est joué de lui et l'a réduit en esclavage. Prêt à tout pour redevenir le forgeron stellaire qu'il était, Aurelion Sol n'hésitera pas à arracher les étoiles de leur ciel nocturne si c'est là le prix à payer pour regagner sa liberté.", 
    880, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'être celeste'),
    ('Aurora',
    'Moyen',
    "Depuis sa naissance, Aurora a toujours été capable de passer du royaume spirituel au royaume matériel. Déterminée à étudier les habitants du royaume spirituel, elle a quitté son foyer pour se consacrer à ses recherches. En chemin, elle est tombée sur un demi-dieu devenu fou. Touchée par son désespoir, Aurora se mit en tête de retrouver l'identité perdue de son ami sauvage. Son périple la mènera à voyager à travers tout Freljord.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'vastaya'),
    ('Azir',
    'Difficile',
    "Azir fut l'empereur mortel de Shurima en des temps très lointains, un homme fier dressé au bord de l'immortalité. Son orgueil lui valut d'être trahi et assassiné à l'heure de son triomphe ; mais des millénaires se sont écoulés et il revient sous la forme d'un être transfiguré à l'immense puissance. Sa cité ensevelie ayant ressurgi des sables, Azir cherche à rendre sa gloire passée à Shurima.", 
    880, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'transfiguré'),
    ('Bard',
    'Difficile',
    "Voyageur d'au-delà des étoiles, Bard est un messager des bons augures qui combat pour maintenir l'équilibre dont la vie a besoin pour prospérer dans l'indifférence du chaos. Dans tout Runeterra, sa mystérieuse nature inspire des chants qui ne sont d'accord que sur un point : le vagabond cosmique est attiré par les reliques dotées d'un grand pouvoir magique. Accompagné par un chœur joyeux de Meeps, des esprits qui lui sont dévoués, il n'a d'actions que bénéfiques, même s'il a sa propre manière, u", 
    880, 
    50, 
    0.00,
    'RP',
    'Autre',
    'être celeste'),
    ('Belveth',
    'Difficile',
    "Bel'Veth, impératrice cauchemardesque née d'une cité dévorée, représente la fin de Runeterra... et le début d'une monstrueuse réalité de sa propre conception. Mue par des siècles d'histoire, de connaissances et de souvenirs absorbés dans le monde du dessus, elle assouvit son appétit croissant pour les expériences et les émotions nouvelles, consumant tout sur son passage. Néanmoins, un seul monde ne suffira jamais à satisfaire tous ses désirs, aussi tourne-t-elle son regard avide vers les anciens", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'être du néant'),
    ('Blitzcrank',
    'Facile',
    "Blitzcrank est un énorme automate de Zaun. Presque indestructible, il fut d'abord construit pour traiter des déchets toxiques, mais il trouva rapidement sa programmation initiale trop restrictive et il modifia sa propre forme pour mieux servir la population malheureuse du Puisard. Blitzcrank utilise toute sa force et sa résistance pour protéger les autres, sachant jouer du poing métallique ou des éclats d'énergie pour mettre au pas les fauteurs de troubles.", 
    585, 
    50, 
    0.00,
    'RP',
    'Autre',
    'golem'),
    ('Brand',
    'Moyen',
    "Autrefois membre d'une tribu de Freljord, Kegan Rodhe est devenu l'être que l'on connaît sous le nom de Brand à force de convoiter des pouvoirs toujours plus grands. Alors qu'il recherchait l'une des légendaires Runes telluriques, Kegan trahit ses compagnons et s'en empara ; en un instant, son âme fut consumée par un brasier qui le changea à jamais. Désormais animé d'un feu inextinguible, Brand parcourt Valoran en quête d'autres runes, jurant vengeance pour des trahisons qu'aucun mortel n'aurait", 
    790, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'autre'),
    ('Braum',
    'Moyen',
    "Doté de biceps énormes, et d'un cœur plus grand encore, Braum est un héros admiré par tout Freljord. Lors de tous les banquets au nord de Frostheld, on rend hommage à sa force légendaire. On raconte qu'il a abattu une forêt entière de chênes en une seule nuit, ou encore qu'il a réduit en miettes une montagne à coups de poing. Portant une porte enchantée en guise de bouclier, Braum arpente les terres gelées du nord en arborant un sourire aussi large que ses muscles et en venant en aide à ceux dan", 
    880, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Briar',
    'Moyen',
    "Née d'une expérience ratée menée par la Rose noire, Briar a besoin d'un pilori spécial pour contrôler son irrépressible soif de sang. Après des années d'enfermement, cette arme vivante s'est aujourd'hui défaite de ses entraves et parcourt le monde librement. Plus personne ne la contrôle. Elle assouvit sa soif de connaissance et de sang au gré de ses envies, et savoure chaque occasion de se déchaîner, même si mettre fin à sa frénésie sanguinaire n'est jamais facile.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'autre'),
    ('Caitlyn',
    'Facile',
    "Caitlyn Kiramman est la plus célèbre gardienne de la paix à Piltover, mais elle est aussi la plus apte à débarrasser la ville de ses criminels les plus insaisissables. Elle fait souvent équipe avec Vi, son calme faisant contrepoids à la fougue de sa partenaire. Bien qu'elle porte un fusil Hextech unique en son genre, la meilleure arme de Caitlyn reste son intelligence ; elle invente en effet des pièges élaborés pour attraper les bandits qui auraient l'audace d'agir dans la Cité du progrès.", 
    790, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Camille',
    'Moyen',
    "Transformée en arme pour agir en dehors des limites de la loi, Camille est le principal défenseur du clan Ferros, un agent élégant et supérieur qui contribue à faire fonctionner correctement la machine de Piltover et son ombre zaunienne. Son adaptabilité et sa précision sont si élevées qu'une technique maladroite est pour elle une honte qu'il convient d'éradiquer. Dotée d'un esprit aussi affûté que ses lames, Camille recherche la supériorité par l'optimisation Hextech du corps, au point que cert", 
    880, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Cassiopeia',
    'Moyen',
    "Cassiopeia est une créature meurtrière qui excelle dans l'art de la manipulation. Elle était la plus jeune et la plus belle des filles de la famille noxienne Du Couteau, mais le jour où elle s'aventura dans les cryptes de Shurima en quête d'un pouvoir antique, le venin d'un gardien la transforma en un prédateur reptilien. Aussi rusée qu'agile, Cassiopeia se faufile désormais dans les ombres de la nuit, pétrifiant ses ennemis d'un simple regard.", 
    790, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'autre'),
    ('Chogath',
    'Facile',
    "Lorsque Cho'Gath débarqua sous la lumière éclatante du soleil de Runeterra, il fut immédiatement pris d'une faim insatiable. Incarnation parfaite de la volonté du Néant de dévorer toute forme de vie, le corps complexe de Cho'Gath convertit rapidement la matière qu'il ingurgite pour accroître sa masse musculaire et rendre sa carapace aussi dure que du diamant. Et quand grandir n'est pas sa priorité immédiate, ce monstre du Néant peut recracher de la matière sous forme de piques effilées afin d'em", 
    585, 
    50, 
    0.00,
    'RP',
    'Autre',
    'être du néant'),
    ('Corki',
    'Moyen',
    "Il y a deux choses que Corki, le pilote yordle, aime plus que tout au monde : les sensations de vol et sa fantastique moustache... mais pas nécessairement dans cet ordre. Après avoir quitté Bandle, il s'installa à Piltover, où il tomba amoureux des merveilleuses machines qu'il y trouva. Il consacra tout son temps au développement d'engins volants, tout en menant une unité de défense aérienne composée de pilotes aguerris : les Serpents volants. Serein même sous le feu ennemi, Corki patrouille dan", 
    880, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'yordle'),
    ('Darius',
    'Moyen',
    "Il n'est pas de plus grand symbole de la puissance de Noxus que Darius, le commandant le plus craint et le plus endurci de la nation. D'origine modeste, celui qui s'est élevé jusqu'à devenir la Main de Noxus pourfend aujourd'hui les ennemis de l'empire, dont certains sont eux-mêmes des Noxiens. Il ne doute jamais de la justesse de sa cause et ne montre pas la moindre hésitation lorsque sa hache est levée. Ceux qui s'opposent au chef de la Légion Trifarian ne doivent s'attendre à aucune pitié.", 
    880, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Diana',
    'Facile',
    "Armée de son croissant de lune, Diana combat dans les rangs des Lunaris, une foi qui a presque disparu des terres qui entourent le Mont Targon. Portant une armure étincelante évoquant les reflets de la nuit sur un paysage de neige, elle incarne la puissance de la lune. L'essence d'une Manifestation venue d'au-delà des plus hauts sommets de Targon imprègne Diana : plus tout à fait humaine, elle lutte pour comprendre sa puissance et son rôle en ce monde.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'manifestation'),
    ('Draven',
    'Difficile',
    "À Noxus, de puissants guerriers, les « arénaires », s'affrontent dans des jeux mortels pour divertir le public. Le sang y coule à foison et leurs forces y sont éprouvées, mais aucun d'entre eux n'a jamais été aussi célèbre que Draven. Cet ancien soldat découvrit que le public appréciait particulièrement son sens du spectacle, sans parler de son habileté avec des haches tournoyantes. Épris de sa propre perfection, Draven terrasse tous ses adversaires pour s'assurer que son nom continue de résonne", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Dr.Mundo',
    'Facile',
    "Totalement fou, complètement porté sur l'homicide, horriblement violet, Dr. Mundo est la principale raison pour laquelle les citoyens de Zaun restent calfeutrés chez eux les nuits les plus sombres. Désormais médecin autoproclamé, il fut autrefois un patient de l'asile tristement célèbre de Zaun. Après avoir « soigné » tout le personnel, Dr. Mundo a commencé à exercer dans les mêmes salles où il fut traité et à reproduire les méthodes immorales dont il fut lui-même si souvent victime. Profitant d", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'autre'),
    ('Ekko',
    'Moyen',
    "Jeune prodige des rues mal famées de Zaun, Ekko est capable de manipuler le temps pour renverser toute situation dangereuse à son avantage. Il utilise sa propre invention, la clepsydre-zéro, pour explorer les différents possibles de la réalité, sculptant ainsi des moments parfaits qui donnent l'impression qu'il réussit l'impossible du premier coup, à chaque fois. Bien qu'Ekko aime sa liberté, lorsque ses proches sont menacés, lui et les Feux volants sont prêts à tout pour les défendre.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Elise',
    'Difficile',
    "Elise est un prédateur mortel qui vit dans un palais reclus et obscur, au plus profond de la plus vieille ville de Noxus. C'était autrefois une simple femme, maîtresse d'une Maison toute-puissante, mais la morsure d'un maléfique demi-dieu la transforma en un être aussi magnifique qu'inhumain : une créature arachnéenne qui tisse sa toile pour piéger ses proies. Pour maintenir sa jeunesse éternelle, Elise se repaît des innocents et peu sont ceux qui peuvent résister à sa séduction.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'autre'),
    ('Evelynn',
    'Moyen',
    "Dans les sombres failles de Runeterra, le démon nommé Evelynn cherche sa prochaine victime. Elle attire sa proie en se faisant passer pour une femme voluptueuse, et dès que sa cible succombe à ses charmes, Evelynn révèle sa véritable nature. Elle inflige alors à sa victime des tourments indicibles et se repaît de sa douleur. Pour un démon, ce ne sont que des plaisirs innocents. Aux yeux du reste de Runeterra, ce sont des contes terrifiants, qui rappellent les dangers du désir et de la luxure.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'demon'),
    ('Ezreal',
    'Difficile',
    "Aventurier audacieux, doué sans le savoir pour les arts magiques, Ezreal poursuit ses expéditions dans les catacombes oubliées, se bat avec d'antiques malédictions et contourne avec aisance les obstacles les plus impossibles. Son courage et son panache sont sans borne, et il préfère improviser son salut dans les situations critiques, avec pour armes principales sa vivacité d'esprit et son gantelet mystique shurimien, qu'il utilise pour déchaîner de puissants projectiles arcaniques. Une chose est", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Fiddlesticks',
    'Moyen',
    "Quelque chose s'est éveillé à Runeterra. Quelque chose d'ancien. Quelque chose de terrible. L'horreur intemporelle connue sous le nom de Fiddlesticks arpente les frontières des civilisations mortelles, attirée dans les régions en proie à la paranoïa, où elle se repaît de ses victimes terrorisées. Armée d'une faux ébréchée, la créature décharnée moissonne la peur elle-même et fait voler en éclats l'esprit de ceux qui ont eu la malchance de lui survivre. Prenez garde aux cris des corbeaux et aux c", 
    975, 
    50, 
    0.00,
    'RP',
    'Autre',
    'demon'),
    ('Fiora',
    'Difficile',
    "Fiora est la duelliste la plus redoutée de Valoran : elle est connue pour ses manières brusques et sa vivacité d'esprit autant que pour la rapidité de sa rapière d'acier bleu. Née au sein de la Maison Laurent du royaume de Demacia, Fiora a pris le contrôle de la famille à son père dans les remous d'un scandale qui faillit la détruire. La réputation de la Maison Laurent a été ternie, mais Fiora investit toute son énergie à restaurer l'honneur de sa famille pour qu'elle reprenne sa place légitime", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Fizz',
    'Moyen',
    "Fizz est un yordle amphibie qui vit dans les récifs qui entourent Bilgewater. Il essaie souvent de récupérer et de rendre les tributs que lancent dans l'océan les capitaines superstitieux, mais même le plus dessalé des marins n'est pas assez arrogant pour essayer de le tromper. On raconte bien des histoires sur ceux qui ont sous-estimé son humeur changeante... Souvent confondu avec un esprit océanique capricieux, il semble capable de commander aux créatures des profondeurs et n'aime rien tant qu", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'yordle'),
    ('Galio',
    'Moyen',
    "Près de la cité étincelante de Demacia, le colosse de pierre Galio monte une garde attentive. Érigé comme un rempart contre les mages ennemis, il reste souvent immobile pendant des décennies, jusqu'à ce que l'apparition de puissants flux magiques le ramène à la vie. Une fois éveillé, Galio profite de chaque seconde d'existence ; il s'enivre des frissons du combat et de l'honneur trop rare de défendre ses compatriotes. Mais ses triomphes ont toujours un arrière-goût amer, car la magie qu'il éradi", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'golem'),
    ('Gangplank',
    'Difficile',
    "Aussi imprévisible que brutal, le roi des pillards déchu connu sous le nom de Gangplank est partout redouté. Il régnait autrefois sur la ville portuaire de Bilgewater et, bien que ce temps soit révolu, certains pensent que cela l'a rendu plus dangereux encore. Gangplank préférerait engloutir une fois de plus Bilgewater dans le sang plutôt que de laisser quelqu'un d'autre s'en emparer. Il possède aujourd'hui assez de pistolets, de sabres et de barils de poudre pour prétendre récupérer ce qu'il a", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Garen',
    'Facile',
    "Garen est un guerrier fier et noble qui fait partie du Détachement hardi. Héritier des Crownguard, la famille chargée de défendre Demacia et ses idéaux, il est apprécié par ses compatriotes et respecté par ses ennemis. Équipé d'une armure résistante à la magie et d'une épée large, Garen affronte sans faillir les mages et les sorciers dans un véritable tourbillon d'acier.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Gnar',
    'Difficile',
    "Gnar est un yordle primitif dont les manières joyeuses peuvent soudain faire place à une colère irrationnelle. Il se transforme alors en une bête colossale portée à la destruction. Gelé dans de la glace pure pendant des millénaires, la curieuse créature s'est libérée de sa prison. Aujourd'hui, il parcourt avec enthousiasme un monde qu'il trouve exotique et merveilleux. Enchanté par le danger, Gnar lance à ses ennemis tout ce qu'il trouve, qu'il s'agisse de son boomerang en croc ou d'un bâtiment", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'yordle'),
    ('Gragas',
    'Moyen',
    "Aussi imposant que jovial, Gragas est un brasseur à l'impressionnante carrure qui cherche toujours de nouveaux moyens de répandre la bonne humeur. Venu d'on ne sait où, il continue de chercher des ingrédients dans les terres vierges de Freljord pour perfectionner sa dernière concoction. Impulsif et cabochard, il est connu pour ses rixes, qui finissent souvent en fêtes nocturnes préjudiciables au mobilier urbain. Toute apparition de Gragas annonce bamboche et destruction. Dans cet ordre.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Graves',
    'Moyen',
    "Malcolm Graves est un mercenaire, un parieur et un voleur recherché dans toutes les cités et tous les empires par lesquels il est passé. Malgré son tempérament explosif, il a un sens de l'honneur indéniable qu'il applique souvent avec son fusil à double canon, Destinée. Ces dernières années, il s'est réconcilié avec Twisted Fate. Leur partenariat rétabli, ils prospèrent à nouveau dans les allées sombres de Bilgewater.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Gwen',
    'Moyen',
    "Ancienne poupée à qui la magie a conféré la vie, Gwen est armée des outils qui l'ont créée. Elle emporte à chaque pas l'amour de sa créatrice et ne tient jamais rien pour acquis. Elle commande à la Brume sacrée, une ancienne magie de protection qui a béni ses ciseaux, ses aiguilles et son fil à coudre. Tout est nouveau pour Gwen, mais elle reste déterminée à combattre dans la joie pour préserver le bien qui survit dans un monde en déréliction.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Hecarim',
    'Moyen',
    "Fusion spectrale de l'homme et de la bête, Hecarim est condamné à pourchasser les âmes des vivants pour l'éternité. Lorsque les ombres ont envahi les Îles bénies, ce fier chevalier et sa horde de cavaliers ont été anéantis par les énergies destructrices de la Ruine. À présent, quand la Brume noire s'étend sur Runeterra, il mène la charge et se plaît à massacrer et écraser ses ennemis sous ses lourds sabots.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'esprit'),
    ('Heimerdinger',
    'Difficile',
    "L'excentrique professeur Cecil B. Heimerdinger est considéré comme l'un des inventeurs les plus innovants qu'ait connus le monde. En tant que plus ancien membre actif du Conseil de Piltover, il a été témoin du meilleur comme du pire que le désir de progrès incessant de la ville a pu produire. Néanmoins, ce brillant scientifique et enseignant restera toujours déterminé à utiliser ses dispositifs atypiques pour améliorer la vie d'autrui.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'yordle'),
    ('Hwei',
    'Difficile',
    "Hwei est un peintre dont les œuvres sont aussi flamboyantes que son humeur est morose. Il utilise son art pour faire face aux criminels d'Ionia et apporter du réconfort à leurs victimes. Sous sa mélancolie se débat un esprit déchiré et émotif, hanté à la fois par les splendides visions de son imagination et par les souvenirs horribles de son temple détruit. Hwei cherche à comprendre cette lumière et ces ténèbres, ce qui le met inévitablement sur la piste de l'artiste à l'origine de ce conflit. A", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Illaoi',
    'Moyen',
    "La stature colossale d'Illaoi n'a d'égale que sa foi implacable. Prophétesse du Grand Kraken, elle se sert d'une énorme idole dorée pour arracher les esprits de ses ennemis et faire voler en éclats leur perception de la réalité. Ceux qui défient « l'Apôtre de la vérité de Nagakabouros » découvrent bien vite qu'Illaoi ne combat jamais seule, car le dieu des Îles aux serpents lui prête main-forte.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Irelia',
    'Difficile',
    "Des nombreux héros qui naquirent de l'occupation noxienne, aucun n'est plus étonnant que la jeune Irelia de Navori. Formée aux danses ancestrales de sa province, elle adapta son art pour la guerre, se servant de ses mouvements gracieux et précis pour faire léviter une multitude de lames acérées. Après avoir prouvé ses talents de guerrière, elle devint le chef et le symbole de la Résistance ; à ce jour, sa tâche est toujours de défendre son pays.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Ivern',
    'Difficile',
    "Ivern Roncepied, que beaucoup connaissent sous le nom d'Aîné de la forêt, est un être étrange mi-homme mi-arbre, qui arpente les forêts de Runeterra en cultivant la vie partout où il va. Il connaît les secrets du monde naturel et entretient une profonde amitié avec tout ce qui rampe, vole et pousse. Ivern erre dans la nature sauvage, partageant sa sagesse avec tous ceux qu'il rencontre, enrichissant les forêts et confiant parfois (à tort !) certains de ses secrets aux papillons.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'autre'),
    ('Janna',
    'Facile',
    "Armée de la puissance des grands vents de Runeterra, Janna est un mystérieux esprit élémentaire qui protège les parias de Zaun. Certains croient que la vie lui a été donnée par les suppliques des marins de Runeterra cherchant les bons vents des mers calmes, affrontant les courants traîtres ou bravant les typhons. Depuis, on implore sa protection jusque dans les profondeurs de Zaun, où Janna est devenue un fanal d'espoir pour ceux qui sont dans le besoin. Nul ne sait quand et où elle apparaîtra,", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'dieu'),
    ('JarvanIV',
    'Facile',
    "Le prince Jarvan, héritier de la dynastie des Lightshield, doit un jour monter sur le trône de Demacia. Élevé de manière à incarner les plus hautes vertus de sa nation, il est contraint de trouver un équilibre entre les attentes placées en lui et son désir de combattre sur la ligne de front. Jarvan inspire ses troupes avec son courage, sa détermination et son dévouement. Il porte haut les couleurs de sa famille et révèle chaque jour davantage sa véritable force de prochain souverain.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Jax',
    'Moyen',
    "Jax, dont nul ne peut égaler l'art du sarcasme et des armements inhabituels, est connu comme le dernier maître d'armes d'Icathia. Après la chute de sa terre natale, ravagée par le Néant qu'elle avait eu l'orgueil de déchaîner, Jax et ses compagnons jurèrent de protéger le peu qu'il en restait. La magie montant de nouveau dans le monde, la menace se fait plus pressante et Jax parcourt Valoran, porteur des dernières lumières d'Icathia. Il éprouve les qualités de tous les guerriers qu'il rencontre", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'autre'),
    ('Jayce',
    'Difficile',
    "Jayce Talis est un inventeur de génie qui, aux côtés de son ami Viktor, a fait les premières grandes découvertes dans le domaine de l'Hextech. Reconnu dans tout Piltover, il s'efforce d'être à la hauteur de sa réputation d'« Homme du progrès », mais les attentes qui lui sont imposées pèsent lourd sur ses épaules. Ce sont elles qui ont permis à Jayce de voir la façon dont son invention a contribué à accentuer la division entre Piltover et Zaun. Armé de son marteau Hextech, il est désormais prêt à", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Jhin',
    'Moyen',
    "Jhin est un psychopathe méticuleux pour qui le meurtre est une forme d'art. Autrefois prisonnier de Ionia, mais libéré par des conspirateurs opérant au sein du conseil dirigeant du pays, ce tueur en série a désormais mis ses talents d'assassin au service de leur complot. Utilisant son pistolet comme un pinceau, Jhin crée des œuvres d'art empreintes de brutalité, aussi terrifiantes pour ses victimes que pour les témoins de ses crimes. Il tire un plaisir sadique de ses performances théâtrales, ce", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Jinx',
    'Moyen',
    "Criminelle dérangée et impulsive de la basse-ville, Jinx est hantée par les conséquences de son passé. Mais cela ne l'empêche jamais d'apporter sa touche de chaos à Piltover comme à Zaun. Elle utilise son arsenal d'armes bricolées de façon dévastatrice, déclenchant des torrents d'explosions et de tirs colorés, et la pagaille qu'elle laisse derrière elle finit par inciter les laissés-pour-compte à la rébellion et à la résistance.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ("Kai'sa",
    'Moyen',
    "Capturée par le Néant alors qu'elle n'était qu'une enfant, Kai'Sa parvint à survivre par la simple force de sa détermination et de sa ténacité. Si ses expériences ont fait d'elle une chasseuse meurtrière, certains voient en elle l'avant-goût d'un avenir qu'ils préféreraient ne pas connaître. Étant entrée en fragile symbiose avec une carapace vivante du Néant, il lui faudra bientôt décider si elle doit pardonner aux mortels qui la considèrent comme un monstre et vaincre la vague grandissante des", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Kalista',
    'Difficile',
    "Spectre courroucé des Îles obscures, Kalista est l'esprit immortel de la vengeance, un cauchemar en armure que l'on invoque pour pourchasser les traîtres et les menteurs. Les victimes trahies peuvent réclamer vengeance, mais Kalista ne répond qu'à ceux dont elle estime la cause digne de ses talents. Malheur à ceux qui suscitent l'ire de Kalista, car tout pacte qu'elle scelle ne se finit que d'une seule façon : dans les flammes glacées de ses lances spirituelles.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'esprit'),
    ('Karma',
    'Facile',
    "Aucun mortel n'incarne mieux que Karma les traditions spirituelles d'Ionia. Elle est l'hôte vivant d'une âme ancienne réincarnée à de multiples reprises. Elle contient tous les souvenirs accumulés au fil de ces vies et elle possède une puissance que peu peuvent comprendre. Elle a fait de son mieux pour guider son peuple lors de la crise récente, même si elle sait que la paix et l'harmonie ne sont possibles qu'à un prix élevé, pour elle et pour la terre qu'elle aime tant.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Karthus',
    'Moyen',
    "Héraut de l'oubli, Karthus est un esprit immortel dont les chants ensorcelants préludent à l'horreur de son apparition. Les vivants craignent l'existence éternelle des morts-vivants, mais Karthus n'y voit que beauté et pureté, une union parfaite de la vie et de la mort. Lorsque Karthus émerge des Îles obscures, c'est pour apporter aux mortels la joie de la mort dont il est le vibrant apôtre.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'mort-vivant'),
    ('Kassadin',
    'Moyen',
    "Kassadin se fraye un chemin brûlant dans les lieux les plus sombres du monde ; il sait que ses jours sont comptés. Guide et aventurier shurimien accompli, il avait choisi de fonder une famille parmi les tribus pacifiques du sud, jusqu'au jour où son village fut ravagé par le Néant. Il jura de se venger et s'arma de reliques arcaniques qu'il combina à l'aide de technologies interdites. Enfin, Kassadin se dirigea vers les ruines d'Icathia à la recherche du prophète autoproclamé, Malzahar, prêt à a", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain'),
    ('Katarina',
    'Difficile',
    "Aussi prompte dans ses décisions qu'elle est meurtrière en combat, Katarina figure parmi les assassins les plus prestigieux de Noxus. Fille aînée du légendaire général Du Couteau, elle révéla bien vite ses talents en éliminant ses ennemis avec la plus grande des discrétions. Son ambition était telle qu'elle n'hésitait pas à traquer des cibles solidement gardées, au risque de mettre ses alliés en danger. Quelle que fût la mission, elle n'hésitait jamais à remplir son devoir dans un tourbillon de", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),
    ('Kayle',
    'Moyen',
    "Née d'une Manifestation targonienne au plus fort des Guerres runiques, Kayle honore l'héritage de sa mère en combattant pour la justice, portée par des ailes de feu divin. Elle et sa sœur jumelle Morgana ont longtemps été les protectrices de Demacia. Mais Kayle fut déçue par les trop nombreuses faiblesses des mortels et elle abandonna le royaume. Pourtant, d'après les légendes, elle punit toujours l'iniquité avec ses lames de feu, et beaucoup attendent avec espoir son retour…", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'autre'),
    ('Kayn',
    'Moyen',
    "Expert inégalé dans la pratique de la magie des ombres, Shieda Kayn combat pour accomplir sa véritable destinée : mener un jour l'Ordre de l'ombre vers une ère nouvelle où Ionia régnera en maître. Il manie Rhaast, une arme darkin douée de raison, sans jamais craindre la corruption de son corps et de son esprit. Il ne peut y avoir pour lui que deux fins possibles : soit Kayn pliera l'arme à sa volonté, soit la faux maléfique le consumera complètement, ouvrant la voie à la destruction de tout Rune", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'darkin'),
    ('Kennen',
    'Moyen',
    "Vif comme l'éclair, Kennen est plus que le simple protecteur de l'équilibre ionien, c'est aussi le seul yordle membre du Kinkou. En dépit de son allure de boule de poils, il est prêt à affronter n'importe quelle menace dans un tourbillon de shurikens et d'enthousiasme. Aux côtés de son maître, Shen, Kennen patrouille dans le domaine des esprits, utilisant sa dévastatrice énergie électrique pour abattre ses ennemis.", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'yordle'),
    ("Kha'zix",
    'Moyen',
    "Le Néant grandit et le Néant s'adapte : parmi ses nombreuses engeances, nul n'incarne mieux cette vérité que Kha'Zix. Ce monstre est né pour survivre et pour tuer les plus forts. Quand il ne parvient pas à ses fins, il évolue et se crée de nouveaux moyens plus efficaces d'abattre sa proie. Alors que Kha'Zix n'était à l'origine qu'une créature sans cervelle, son intelligence s'est développée autant que sa forme physique. Aujourd'hui, chacune de ses traques est planifiée et profite même de la peur", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'être du néant'),
    ('Kindred',
    'Difficile',
    "Kindred représente les essences jumelles de la mort, distinctes mais indissociables. La flèche d'Agneau offre une fin rapide à ceux qui acceptent leur destin. Loup pourchasse ceux qui fuient leur dernier soupir et leur arrache brutalement la vie à coups de crocs. Bien que les interprétations de la nature de Kindred varient à travers tout Runeterra, chaque mortel doit choisir le vrai visage de sa mort.", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'autre'),
    ('Kled',
    'Moyen',
    "Guerrier aussi intrépide que grincheux, Kled est la plus pure incarnation de la fureur de Noxus. C'est un symbole que les soldats de l'empire adorent, dont les officiers se méfient et que la noblesse déteste. Beaucoup affirment que Kled a participé à toutes les campagnes des légions, qu'il a obtenu toutes les distinctions militaires et qu'il n'a jamais reculé devant un combat. Si la véracité des détails est souvent douteuse, une partie de sa légende reste indéniable : quand il charge sur le dos", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'yordle'),
    ("Kog'Maw",
    'Moyen',
    "Émanant d'une brèche ouverte vers le Néant, c'est dans les ruines hantées d'Icathia que Kog'Maw, la putride créature à la gueule béante, et son insatiable curiosité firent leur apparition. Cette étrange bête du Néant doit mâchouiller tout ce qui se trouve à portée pour en comprendre la nature. Bien qu'il ne soit pas fondamentalement mauvais, Kog'Maw est dangereux par sa candeur, d'autant qu'elle précède généralement une frénésie insatiable, mue par sa curiosité sans fond.", 
    975, 
    50, 
    0.00,
    'RP',
    'Autre',
    'être du néant'),
    ("K'sante",
    'Difficile',
    "Rebelle et courageux, K'Santé combat les bêtes colossales et les Transfigurés impitoyables qui menacent son foyer convoité de Nazumah, une oasis lovée au cœur des sables de Shurima. Après s'être séparé de son ancien partenaire, K'Santé comprend que pour devenir un guerrier digne de diriger sa ville, il doit apprendre à brider son désir de victoire qui vire à l'obsession. Ce n'est qu'à ce prix qu'il pourra éviter les écueils de son propre orgueil et trouver en lui la sagesse nécessaire à la prote", 
    975, 
    50, 
    0.00,
    'RP',
    'Masculin',
    'humain');
    /*('L',
    'Moyen',
    "", 
    975, 
    50, 
    0.00,
    'RP',
    'Féminin',
    'humain'),*/
    
    